[profile.default]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/_zx76GqlQpcxutEzWiwiqmuzLFh6ZNML"